name: JJLeathersmith
favicon: null
layout_spectrum: 0.52155
typography_spectrum: 0.69759
title: JJ Leathersmith
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff7d44'
    - '#511f00'
    - '#837f75'
    - '#a0d9f4'
  brandStrength: 0.0625
  lightness: 0.4375
  saturation: 0.9375
  rhythmicContrast: 0
purpose: []
