name: JJLeathersmith
favicon: null
layout_spectrum: 0.0359527540858835
typography_spectrum: 0.11260114633478224
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff7d44'
    - '#511f00'
    - '#837f75'
    - '#a0d9f4'
  brandStrength: 0.625
  lightness: 0.41035881638526917
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
