name: JJLeathersmith
favicon: null
layout_spectrum: 0.01767
typography_spectrum: 0.7183
title: JJ Leathersmith
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d4e8ec'
    - '#88acb8'
    - '#120b05'
    - '#c04c30'
    - '#f3bc99'
  brandStrength: 0
  lightness: 0.4375
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
